spring:
  application:
    name: CourseProjectVM
  datasource:
    url: ${DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${USER_NAME:test}
    password: ${PASSWORD:Vo3wMG71W6h1aRF4ZPZymdVNdphyyE2M}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
